In [1]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('severe_out.csv', keep_default_na=True)
N = 849

In [7]:
dataset.to_csv('vacc_out.csv', index=False)

In [4]:
# By vaccination status
total = np.array([30,819])
vaccination_status = dataset['Vaccination'].unique()
print(vaccination_status)

by_vaccination_status = np.zeros((len(vaccination_status), 2))

for i, status in enumerate(vaccination_status):
    for j in range(2):
        if pd.isna(status):
            by_vaccination_status[i, j] = dataset[(pd.isna(dataset['Vaccination'])) & (dataset['outcome_died'] == 1 - j)].shape[0]
        else:
            by_vaccination_status[i, j] = dataset[(dataset['Vaccination'] == status) & (dataset['outcome_died'] == 1 - j)].shape[0]
by_vaccination_status[3] += by_vaccination_status[4]
print(by_vaccination_status[:4])

percent = by_vaccination_status / total * 100
print(percent[:4])

[ 0. nan  1.  2.  3.]
[[ 26. 761.]
 [  1.  25.]
 [  2.  27.]
 [  1.   6.]]
[[86.66666667 92.91819292]
 [ 3.33333333  3.05250305]
 [ 6.66666667  3.2967033 ]
 [ 3.33333333  0.73260073]]


In [5]:
print(np.median(dataset['age_at_admission']))
print(np.std(dataset['age_at_admission']))

x = np.percentile(dataset['age_at_admission'], [25, 50, 75])
x

8.0
20.56709186420721


array([ 5.,  8., 12.])

In [6]:
x = 759 / 849 * 100
y = 787 / 849 * 100
y

92.69729093050648

In [7]:
# Age group (in months)

age_group = ['0 - 1','1 - 2','2 - 3','3 - 4','4 - 5','>= 5']
x = np.zeros((6,2))
total = np.array([30,819])

for i in range(6):
    for j in range(2):
        x[i,j] = len(dataset[(dataset['Age group (in years)'] == age_group[i]) & (dataset['outcome_died'] == 1 - j)])

print(age_group)
print(x)
print(np.round(x*100/total,1))

['0 - 1', '1 - 2', '2 - 3', '3 - 4', '4 - 5', '>= 5']
[[ 18. 609.]
 [  3. 125.]
 [  1.  27.]
 [  1.  20.]
 [  1.   8.]
 [  6.  30.]]
[[60.  74.4]
 [10.  15.3]
 [ 3.3  3.3]
 [ 3.3  2.4]
 [ 3.3  1. ]
 [20.   3.7]]


In [12]:
dataset = pd.read_csv('vacc_out.csv', keep_default_na=True)
N = 399
print(len(dataset.loc[(dataset['Age group (in months)'] != '0 - 9')]))
unvacc = len(dataset.loc[(dataset['Age group (in months)'] != '0 - 9') & (dataset['New vaccination'] == '0')])
print(unvacc, unvacc/N*100)
dead = len(dataset.loc[(dataset['Age group (in months)'] == '0 - 9') & (dataset['outcome_died'] == 1)])
print(dead, dead/30*100)

399
354 88.7218045112782
12 40.0


In [11]:
for i in range(10):
    print(dataset.at[i,'age_at_admission'], dataset.at[i,'Age group (in months)'])

19 9 - 60
3 0 - 9
11 9 - 60
34 9 - 60
12 9 - 60
6 0 - 9
17 9 - 60
3 0 - 9
6 0 - 9
71 >= 60
