In [1]:
import pandas as pd
import numpy as np
import datetime
import string
import os
from matplotlib import pyplot as plt
from pathlib import Path

In [3]:
RAW_DATA_PATH = '/Users/vuhoangnguyen/Research/'
RAW_DATA = os.path.join(RAW_DATA_PATH, 'raw_data.csv')
raw_dataset = pd.read_csv(RAW_DATA, keep_default_na=False)
DATA = os.path.join(Path.cwd().parents[0], 'Data/out.csv')
dataset = pd.read_csv(DATA, keep_default_na=False)

In [11]:
place = ['community','Another hospital','NHP']
table = np.zeros((3,3))

for i, year in enumerate(['2017', '2018', '2019']):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['admission_date'].str.contains(year)) ])

print(table)
print(np.round(100 * table/np.sum(table, axis=0), 1))
print(np.sum(table, axis=1))

[[ 61.   8.  61.]
 [382.  67. 171.]
 [838. 166. 315.]]
[[ 4.8  3.3 11.2]
 [29.8 27.8 31.3]
 [65.4 68.9 57.6]]
[ 130.  620. 1319.]


In [12]:
place = ['community','Another hospital','NHP']
table = np.zeros((2,3))

for i in range(2):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['Female'] == i) ])

print(table)
print(np.round(100 * table/np.sum(table, axis=0), 1))
print(np.sum(table, axis=1))

[[787. 161. 348.]
 [494.  80. 199.]]
[[61.4 66.8 63.6]
 [38.6 33.2 36.4]]
[1296.  773.]


In [ ]:
month_group = [0,3,6,9,12,24,36,48,60]
age_group = ['0 - <3','3 - <6','6 - <9','9 - <12','12 - <24','24 - <36','36 - <48','48 - <60','>= 60']
row = [(age_group[i],0) for i in range(len(age_group))]
patient_per_age_group = [[0] * 3 for _ in range(len(age_group))]

for id, arr in enumerate(ids_each_place):
    for i in arr:
        val = decimal_month_at_admission[i]
        for j in range(len(month_group)-1,-1,-1):
            if val >= month_group[j]:
                patient_per_age_group[j][id] += 1
                break

for i in range(len(patient_per_age_group)):
    for j in range(len(patient_per_age_group[i])):
        val = patient_per_age_group[i][j]
        total = patient_per_place[j]
        percent = str(round(val*100/total,1)) + '%'
        patient_per_age_group[i][j] = str(val) + ' (' + percent + ')'

age_group_db = pd.DataFrame([[age_group[i]]+patient_per_age_group[i] for i in range(len(age_group))],
                            columns=['Age groups (in months)']+first_row_val)
display(age_group_db)

In [18]:
place = ['community','Another hospital','NHP']
vac = ['0','1','2','3','NA']
table = np.zeros((5,3))

for i in range(5):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset['Vaccination'] == vac[i])])

np.set_printoptions(suppress=True)
print(table)
print(np.round(100 * table/np.sum(table, axis=0),1))
print(np.sum(table, axis=1))

[[1074.  222.  509.]
 [ 142.   11.   19.]
 [  24.    2.    3.]
 [   2.    0.    1.]
 [  39.    6.   15.]]
[[83.8 92.1 93.1]
 [11.1  4.6  3.5]
 [ 1.9  0.8  0.5]
 [ 0.2  0.   0.2]
 [ 3.   2.5  2.7]]
[1805.  172.   29.    3.   60.]


In [22]:
place = ['community','Another hospital','NHP']
table = np.zeros((4,3))
distance = ['0 - <20','20 - <200','200 - <500','>= 500']

for i in range(4):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset['Distance from the hospital (km)'] == distance[i])])

print(table)
print(np.round(100 * table/np.sum(table, axis=0),1))
print(np.sum(table, axis=1))

[[347.  45.  76.]
 [764. 143. 375.]
 [164.  51.  90.]
 [  6.   2.   6.]]
[[27.1 18.7 13.9]
 [59.6 59.3 68.6]
 [12.8 21.2 16.5]
 [ 0.5  0.8  1.1]]
[ 468. 1282.  305.   14.]


In [19]:
place = ['community','Another hospital','NHP']
table = np.zeros((6,3))
part_of_vietnam = ['Ha Noi','Northeastern','Northwestern','Red River Delta (except Hanoi)','Central','Southern']

for i in range(6):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset['region_of_address'] == part_of_vietnam[i])])

print(table)
print(np.round(100 * table/np.sum(table, axis=0),1))
print(np.sum(table, axis=1))

[[503.  67. 144.]
 [117.  29.  61.]
 [ 63.   9.  28.]
 [424.  81. 214.]
 [169.  54.  98.]
 [  5.   1.   2.]]
[[39.3 27.8 26.3]
 [ 9.1 12.  11.2]
 [ 4.9  3.7  5.1]
 [33.1 33.6 39.1]
 [13.2 22.4 17.9]
 [ 0.4  0.4  0.4]]
[714. 207. 100. 719. 321.   8.]


In [23]:
place = ['community','Another hospital','NHP']
table = np.zeros((2,3))

for i in range(2):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['outcome_died'] == i)])
print(table)
print(np.round(100 * table/np.sum(table, axis=0),1))
print(np.sum(table, axis=1))

[[1272.  232.  535.]
 [   9.    9.   12.]]
[[99.3 96.3 97.8]
 [ 0.7  3.7  2.2]]
[2039.   30.]


In [26]:
place = ['community','Another hospital','NHP']
table = np.zeros((5,3))
duration = ['<0','0 - <3','3 - <7','7 - <14', '>= 14']

for i in range(5):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['Duration between onset and admission'] == duration[i])])

print(table)
print(np.round(100 * table/np.sum(table, axis=0),1))
print(np.sum(table, axis=1))

[[259.  52. 298.]
 [652. 107. 154.]
 [303.  64.  85.]
 [ 29.  10.   8.]
 [ 36.   8.   2.]]
[[20.3 21.6 54.5]
 [51.  44.4 28.2]
 [23.7 26.6 15.5]
 [ 2.3  4.1  1.5]
 [ 2.8  3.3  0.4]]
[609. 913. 452.  47.  46.]
2067.0
