In [1]:
import pandas as pd
import numpy as np
import datetime
import string
import os
from matplotlib import pyplot as plt
from pathlib import Path

In [2]:
RAW_DATA_PATH = '/Users/vuhoangnguyen/Research/'
RAW_DATA = os.path.join(RAW_DATA_PATH, 'raw_data.csv')
raw_dataset = pd.read_csv(RAW_DATA, keep_default_na=False)
DATA = os.path.join(Path.cwd().parents[0], 'Data/out.csv')
dataset = pd.read_csv(DATA, keep_default_na=False)

In [83]:
place = ['community','Another hospital','NHP']
total = np.zeros(3)
for i in range(3):
    total[i] = len(dataset[dataset['place_of_exposure'] == place[i]])
total

array([1281.,  241.,  547.])

In [4]:
dataset['admission_years'].value_counts()

KeyError: 'admission_years'

In [84]:
place = ['community','Another hospital','NHP']
table = np.zeros((3,3))

for i, year in enumerate(['2017', '2018', '2019']):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['admission_date'].str.contains(year)) ])

print(table)
print(np.round(100 * table/total, 1))
print(np.sum(table, axis=1))

[[ 61.   8.  61.]
 [382.  67. 171.]
 [838. 166. 315.]]
[[ 4.8  3.3 11.2]
 [29.8 27.8 31.3]
 [65.4 68.9 57.6]]
[ 130.  620. 1319.]


In [85]:
place = ['community','Another hospital','NHP']
table = np.zeros((2,3))

for i in range(2):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['Female'] == i) ])

print(table)
print(np.round(100 * table/total, 1))
print(np.sum(table, axis=1))

[[787. 161. 348.]
 [494.  80. 199.]]
[[61.4 66.8 63.6]
 [38.6 33.2 36.4]]
[1296.  773.]


In [86]:
place = ['community','Another hospital','NHP']
age_group = ['0 - <3','3 - <6','6 - <9','9 - <12','12 - <24','24 - <36','36 - <48','48 - <60','>= 60']
table = np.zeros((9,3))

for i in range(9):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['Age group (in months)'] == age_group[i]) ])

print(table)
print(np.round(100 * table/total, 1))
print(np.sum(table, axis=1))

[[ 45.  10.  32.]
 [150.  33. 108.]
 [314.  65. 143.]
 [282.  68. 106.]
 [197.  39.  78.]
 [ 70.   9.  27.]
 [ 47.   7.  18.]
 [ 28.   2.   5.]
 [148.   8.  30.]]
[[ 3.5  4.1  5.9]
 [11.7 13.7 19.7]
 [24.5 27.  26.1]
 [22.  28.2 19.4]
 [15.4 16.2 14.3]
 [ 5.5  3.7  4.9]
 [ 3.7  2.9  3.3]
 [ 2.2  0.8  0.9]
 [11.6  3.3  5.5]]
[ 87. 291. 522. 456. 314. 106.  72.  35. 186.]
2069.0


In [87]:
place = ['community','Another hospital','NHP']
vac = ['0','1','2','3','NA']
table = np.zeros((5,3))

for i in range(5):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset['Vaccination'] == vac[i])])

np.set_printoptions(suppress=True)
print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[1074.  222.  509.]
 [ 142.   11.   19.]
 [  24.    2.    3.]
 [   2.    0.    1.]
 [  39.    6.   15.]]
[[83.8 92.1 93.1]
 [11.1  4.6  3.5]
 [ 1.9  0.8  0.5]
 [ 0.2  0.   0.2]
 [ 3.   2.5  2.7]]
[1805.  172.   29.    3.   60.]


In [88]:
place = ['community','Another hospital','NHP']
table = np.zeros((4,3))
distance = ['0 - <20','20 - <200','200 - <500','>= 500']

for i in range(4):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset['Distance from the hospital (km)'] == distance[i])])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[347.  45.  76.]
 [764. 143. 375.]
 [164.  51.  90.]
 [  6.   2.   6.]]
[[27.1 18.7 13.9]
 [59.6 59.3 68.6]
 [12.8 21.2 16.5]
 [ 0.5  0.8  1.1]]
[ 468. 1282.  305.   14.]


In [89]:
place = ['community','Another hospital','NHP']
table = np.zeros((6,3))
part_of_vietnam = ['Ha Noi','Northeastern','Northwestern','Red River Delta (except Hanoi)','Central','Southern']

for i in range(6):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset['region_of_address'] == part_of_vietnam[i])])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[503.  67. 144.]
 [117.  29.  61.]
 [ 63.   9.  28.]
 [424.  81. 214.]
 [169.  54.  98.]
 [  5.   1.   2.]]
[[39.3 27.8 26.3]
 [ 9.1 12.  11.2]
 [ 4.9  3.7  5.1]
 [33.1 33.6 39.1]
 [13.2 22.4 17.9]
 [ 0.4  0.4  0.4]]
[714. 207. 100. 719. 321.   8.]


In [90]:
place = ['community','Another hospital','NHP']
table = np.zeros((2,3))

for i in range(2):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['outcome_died'] == i)])
print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[1272.  232.  535.]
 [   9.    9.   12.]]
[[99.3 96.3 97.8]
 [ 0.7  3.7  2.2]]
[2039.   30.]


In [91]:
place = ['community','Another hospital','NHP']
table = np.zeros((5,3))
duration = ['<0','0 - <3','3 - <7','7 - <14', '>= 14']

for i in range(5):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['Duration between onset and admission'] == duration[i])])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[259.  52. 298.]
 [652. 107. 154.]
 [303.  64.  85.]
 [ 29.  10.   8.]
 [ 36.   8.   2.]]
[[20.2 21.6 54.5]
 [50.9 44.4 28.2]
 [23.7 26.6 15.5]
 [ 2.3  4.1  1.5]
 [ 2.8  3.3  0.4]]
[609. 913. 452.  47.  46.]


In [92]:
place = ['community','Another hospital','NHP']
table = np.zeros((3,3))
duration = ['0 - <7','7 - <21', '>= 21']

for i in range(3):
    for j in range(3):
        table[i][j] = len(dataset[ (dataset['place_of_exposure'] == place[j]) & (dataset['Duration of stay within the hospital'] == duration[i])])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[817.  78. 146.]
 [404. 125. 209.]
 [ 60.  38. 192.]]
[[63.8 32.4 26.7]
 [31.5 51.9 38.2]
 [ 4.7 15.8 35.1]]
[1041.  738.  290.]


In [93]:
place = ['community','Another hospital','NHP']
table = np.zeros((9,3))

underlying_condition = ['Underlying conditions - Respiratory system','Underlying conditions - Cardiovascular system',
    'Underlying condition - Gastrointestinal system','Underlying condition - Kidney and urology system',
    'Underlying condition - Immunodeficiency','Underlying condition - Neurological system','Underlying condition - Inherited metabolic disorders',
    'Underlying condition - No underlying diseases','Underlying condition - Other underlying conditions']

for i in range(9):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset[underlying_condition[i]] == 1)])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[  16.    3.   23.]
 [  37.    7.   28.]
 [  42.    2.   50.]
 [  11.    2.   33.]
 [   4.    1.    7.]
 [  22.    5.   46.]
 [   9.    1.    4.]
 [1092.  206.  285.]
 [  55.   14.   90.]]
[[ 1.2  1.2  4.2]
 [ 2.9  2.9  5.1]
 [ 3.3  0.8  9.1]
 [ 0.9  0.8  6. ]
 [ 0.3  0.4  1.3]
 [ 1.7  2.1  8.4]
 [ 0.7  0.4  0.7]
 [85.2 85.5 52.1]
 [ 4.3  5.8 16.5]]
[  42.   72.   94.   46.   12.   73.   14. 1583.  159.]


In [94]:
place = ['community','Another hospital','NHP']
form = ['oxygen_cannula','CPAP','conventional_mechanical_ventilation','hfo_ventilation','ECMO']
table = np.zeros((5,3))

for i in range(5):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset['highest_ventilation_mode'] == form[i])])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[335.  93. 256.]
 [  2.   1.   5.]
 [ 46.  32.  66.]
 [  1.   5.   5.]
 [  1.   0.   0.]]
[[26.2 38.6 46.8]
 [ 0.2  0.4  0.9]
 [ 3.6 13.3 12.1]
 [ 0.1  2.1  0.9]
 [ 0.1  0.   0. ]]
[684.   8. 144.  11.   1.]


In [95]:
place = ['community','Another hospital','NHP']
duration = ['< 0', '0 - <24','24 - <48','>= 48']
table = np.zeros((4,3))

for i in range(4):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset['Duration between onset and test (detection time) (in hours)'] == duration[i])])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))
print(np.sum(table))

[[ 14.   3.   5.]
 [315.  45. 193.]
 [264.  47. 127.]
 [688. 146. 222.]]
[[ 1.1  1.2  0.9]
 [24.6 18.7 35.3]
 [20.6 19.5 23.2]
 [53.7 60.6 40.6]]
[  22.  553.  438. 1056.]
2069.0


In [96]:
place = ['community','Another hospital','NHP']
diagnosis = ['Measles','Pneumonia','Bronchopneumonia','Other diagnosis']
table = np.zeros((4,3))

for i in range(4):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset[diagnosis[i]] == 1)])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[612.  85. 150.]
 [374. 109. 178.]
 [440. 100. 209.]
 [185.  35. 169.]]
[[47.8 35.3 27.4]
 [29.2 45.2 32.5]
 [34.3 41.5 38.2]
 [14.4 14.5 30.9]]
[847. 661. 749. 389.]


In [97]:
place = ['community','Another hospital','NHP']
prefix = 'complication-'
column_name = ['gastroentiritis','middle-ear-infec','conjunctivitis','laryngitis','pneumonia-bronchitis',
'febrile-seizures','septic-shock-sepsis']
table = np.zeros((7,3))

for i in range(7):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset[prefix+column_name[i]] == 1)])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[ 34.   4.  12.]
 [ 19.   3.   8.]
 [  2.   0.   0.]
 [  5.   0.   2.]
 [823. 196. 393.]
 [  2.   1.   7.]
 [  4.   0.   0.]]
[[ 2.7  1.7  2.2]
 [ 1.5  1.2  1.5]
 [ 0.2  0.   0. ]
 [ 0.4  0.   0.4]
 [64.2 81.3 71.8]
 [ 0.2  0.4  1.3]
 [ 0.3  0.   0. ]]
[  50.   30.    2.    7. 1412.   10.    4.]


In [98]:
place = ['community','Another hospital','NHP']
prefix = 'co-infection-'
column_name = ['influenza-a','influenza-b','streptococus-aerius','streptococus-pneumonia']
table = np.zeros((4,3))

for i in range(4):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset[prefix+column_name[i]] == 1)])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[10.  1.  5.]
 [ 2.  0.  2.]
 [ 1.  0.  2.]
 [ 0.  1.  1.]]
[[0.8 0.4 0.9]
 [0.2 0.  0.4]
 [0.1 0.  0.4]
 [0.  0.4 0.2]]
[16.  4.  3.  2.]


In [99]:
place = ['community','Another hospital','NHP']
column_name = ['respiratory_syncytical_virus', 'adenovirus', 'pertussis', 'healthcare_associated_infection']
table = np.zeros((4,3))

for i in range(4):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset[column_name[i]] == 1)])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[ 9.  1. 20.]
 [37. 19. 38.]
 [ 5.  3.  9.]
 [ 1.  4. 13.]]
[[0.7 0.4 3.7]
 [2.9 7.9 6.9]
 [0.4 1.2 1.6]
 [0.1 1.7 2.4]]
[30. 94. 17. 18.]


In [100]:
place = ['community','Another hospital','NHP']
table = np.zeros((2,3))

for i in range(2):
    for j in range(3):
        table[i][j] = len(dataset[(dataset['place_of_exposure'] == place[j]) & (dataset['Clinical classification'] == 1-i)])

print(table)
print(np.round(100 * table/total,1))
print(np.sum(table, axis=1))

[[385. 131. 332.]
 [896. 110. 215.]]
[[30.1 54.4 60.7]
 [69.9 45.6 39.3]]
[ 848. 1221.]
